chore: include requires docker script to be sure we have docker running
Long time ago we introduced a check and a retry mechanism, during one of my
QA shifts, there are still repositories failing with:

$ docker build ...
ERROR: Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?

this adds the retry mechanism to the global docker:build job

Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>